<%@ PAGE LANGUAGE="JAVA" CONTENTTYPE="TEXT/HTML; CHARSET=ISO-8859-1"
    PAGEENCODING="ISO-8859-1"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN" "HTTP://WWW.W3.ORG/TR/HTML4/LOOSE.DTD">

<H1>WELCOME TO PAGE(JSP): ${PAGENO}</H1>